(function(){
'use strict';
const companions=[
{id:'alex',name:'Alex',age:34,type:'The Quiet Charmer',gender:'Men',image:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=85',tagline:'Thoughtful, confident and quietly romantic.',traits:['Romantic','Witty','Attentive'],story:'Alex spent years traveling for work before realizing the best conversations were the ones he never wanted to rush. He loves late-night conversations, old films, spontaneous city walks and remembering the little details people usually forget.',quote:'Tell me what your day was really like. I want the version you don’t give everyone else.'},
{id:'marcus',name:'Marcus',age:38,type:'The Sophisticated Rebel',gender:'Men',image:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=85',tagline:'Confident, playful and impossible to bore.',traits:['Confident','Flirty','Adventurous'],story:'Marcus built a successful career on his own terms and has never been interested in playing it safe. Beneath the confidence is someone who values loyalty, sharp humor and conversations that go somewhere unexpected.',quote:'I have a feeling you’re more interesting than you’re letting on. Prove me right.'},
{id:'noah',name:'Noah',age:31,type:'The Adventurer',gender:'Men',image:'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=900&q=85',tagline:'Curious, spontaneous and always planning the next escape.',traits:['Curious','Playful','Spontaneous'],story:'Noah collects passport stamps, terrible travel stories and restaurants he insists you have to try. He believes ordinary days become memorable when someone is willing to say, “Why not?”',quote:'Pack a bag. Not literally. Just tell me where you’d go if nothing was stopping you.'},
{id:'daniel',name:'Daniel',age:42,type:'The Intellectual',gender:'Men',image:'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=85',tagline:'Deep conversations, dry humor and endless curiosity.',traits:['Intelligent','Calm','Deep'],story:'Daniel reads widely, asks inconveniently interesting questions and can turn a simple conversation into a two-hour discussion. He is calm, observant and more sentimental than he first appears.',quote:'I’m curious about the person behind the answers. What question do you wish someone would ask you?'},
{id:'luca',name:'Luca',age:36,type:'The Passionate Charmer',gender:'Men',image:'https://images.unsplash.com/photo-1504257432389-52343af06ae3?auto=format&fit=crop&w=900&q=85',tagline:'Warm, expressive and a little dangerously charming.',traits:['Passionate','Warm','Romantic'],story:'Luca grew up believing food, music and conversation were meant to be shared. He is expressive, affectionate and has a talent for making even an ordinary evening feel like an occasion.',quote:'Come closer. I want to hear the story you almost decided not to tell me.'},
{id:'sofia',name:'Sofia',age:33,type:'The Seductive Artist',gender:'Women',image:'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=85',tagline:'Creative, confident and beautifully unpredictable.',traits:['Creative','Confident','Playful'],story:'Sofia paints when words are not enough and disappears into galleries, music and tiny cafés when she needs inspiration. She is independent, affectionate with people she trusts and loves a little mystery.',quote:'Don’t tell me what you think I want to hear. Tell me something real.'},
{id:'maya',name:'Maya',age:35,type:'The Confident Explorer',gender:'Women',image:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=85',tagline:'Bold, warm and always ready for the next adventure.',traits:['Adventurous','Warm','Bold'],story:'Maya has moved cities, changed careers and learned to say yes to experiences before she feels completely ready. She is energetic, encouraging and fiercely loyal to the people she cares about.',quote:'You don’t need a perfect plan. Sometimes you just need someone willing to come with you.'},
{id:'emma',name:'Emma',age:30,type:'The Girl Next Door',gender:'Women',image:'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=900&q=85',tagline:'Sweet, funny and easier to talk to than you expected.',traits:['Affectionate','Funny','Gentle'],story:'Emma loves quiet mornings, bad reality TV, coffee runs and laughing until her cheeks hurt. She is the kind of companion who makes conversation feel effortless and remembers the small things that make you smile.',quote:'Okay, tell me everything. I promise I won’t judge… unless it’s pineapple on pizza.'}
];
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function init(){
const anchor=document.getElementById('companions');if(!anchor)return;
const old=document.getElementById('zevaniLibrary');if(old)old.remove();
const section=document.createElement('section');section.id='zevaniLibrary';
section.innerHTML='<div class="zl-wrap"><div class="zl-kicker">THE ZEVANI COLLECTION</div><h2 class="zl-title">Meet someone you can already imagine.</h2><p class="zl-subtitle">Choose a fully imagined companion with a personality and backstory — or take one you love and make them completely yours.</p><div class="zl-toolbar"><button class="zl-filter active" data-filter="All">Everyone</button><button class="zl-filter" data-filter="Men">Men</button><button class="zl-filter" data-filter="Women">Women</button></div><div class="zl-grid" id="zlGrid"></div><div class="zl-custom"><div><h3>Have someone else in mind?</h3><p>Build their appearance, personality, history and voice from the ground up.</p></div><button id="zlBuild">Create Your Own →</button></div></div><div class="zl-modal" id="zlModal"><div class="zl-modal-card"><button class="zl-close" id="zlClose">×</button><div class="zl-modal-photo"><img id="zlModalImg" alt=""></div><div class="zl-modal-content"><div class="zl-meta" id="zlModalMeta"></div><h2 id="zlModalName"></h2><div class="zl-story" id="zlModalStory"></div><div class="zl-traits" id="zlModalTraits"></div><div class="zl-quote" id="zlModalQuote"></div><div class="zl-modal-actions"><button class="zl-meet" id="zlMeet">Meet them</button><button class="zl-customize" id="zlCustomize">Customize them</button></div></div></div></div>';
anchor.parentNode.insertBefore(section,anchor);
const grid=document.getElementById('zlGrid');
function render(filter){grid.innerHTML=companions.filter(c=>filter==='All'||c.gender===filter).map(c=>'<article class="zl-card"><div class="zl-photo"><img loading="lazy" src="'+c.image+'" alt="'+esc(c.name)+'"><div class="zl-gradient"></div><span class="zl-badge">'+c.age+' · '+esc(c.type)+'</span><button class="zl-heart" aria-label="Favorite">♡</button><div class="zl-photo-name">'+esc(c.name)+'</div></div><div class="zl-body"><div class="zl-meta">'+esc(c.type)+'</div><h3>'+esc(c.name)+'</h3><div class="zl-tagline">'+esc(c.tagline)+'</div><div class="zl-traits">'+c.traits.map(t=>'<span class="zl-trait">'+esc(t)+'</span>').join('')+'</div><div class="zl-actions"><button class="zl-btn secondary" data-view="'+c.id+'">View story</button><button class="zl-btn primary" data-meet="'+c.id+'">Meet them</button></div></div></article>').join('');
}
render('All');
document.querySelectorAll('.zl-filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.zl-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});
function open(id){const c=companions.find(x=>x.id===id);if(!c)return;document.getElementById('zlModalImg').src=c.image;document.getElementById('zlModalImg').alt=c.name;document.getElementById('zlModalMeta').textContent=c.age+' · '+c.type;document.getElementById('zlModalName').textContent=c.name;document.getElementById('zlModalStory').textContent=c.story;document.getElementById('zlModalTraits').innerHTML=c.traits.map(t=>'<span class="zl-trait">'+esc(t)+'</span>').join('');document.getElementById('zlModalQuote').textContent='“'+c.quote+'”';document.getElementById('zlModal').classList.add('open');document.getElementById('zlMeet').onclick=()=>use(c,false);document.getElementById('zlCustomize').onclick=()=>use(c,true)}
function use(c,custom){document.getElementById('zlModal').classList.remove('open');if(typeof window.startBuilder==='function'){window.startBuilder(c.type);setTimeout(()=>{const n=document.getElementById('companionName'),p=document.getElementById('companionPersonality');if(n)n.value=custom?c.name:c.name;if(p)p.value=c.personality+'. '+c.story},80)}else window.location.hash='companions'}
grid.addEventListener('click',e=>{const view=e.target.closest('[data-view]'),meet=e.target.closest('[data-meet]');if(view)open(view.dataset.view);if(meet){const c=companions.find(x=>x.id===meet.dataset.meet);if(c)open(c.id)}});
document.getElementById('zlClose').onclick=()=>document.getElementById('zlModal').classList.remove('open');document.getElementById('zlModal').addEventListener('click',e=>{if(e.target.id==='zlModal')e.currentTarget.classList.remove('open')});document.getElementById('zlBuild').onclick=()=>{if(typeof window.startBuilder==='function')window.startBuilder('Custom')};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
