(function(){
'use strict';
const companions=[
{id:'alex',name:'Alex',age:34,type:'The Quiet Charmer',gender:'Men',category:'Romantic',image:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=85',tagline:'Thoughtful, confident and quietly romantic.',traits:['Romantic','Witty','Attentive'],personality:'thoughtful, confident, quietly romantic and attentive',story:'Alex spent years traveling for work before realizing the best conversations were the ones he never wanted to rush. He loves late-night conversations, old films, spontaneous city walks and remembering the little details people usually forget.',quote:'Tell me what your day was really like. I want the version you don’t give everyone else.'},
{id:'marcus',name:'Marcus',age:38,type:'The Sophisticated Rebel',gender:'Men',category:'Flirty',image:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=85',tagline:'Confident, playful and impossible to bore.',traits:['Confident','Flirty','Adventurous'],personality:'confident, playful, flirty, adventurous and loyal',story:'Marcus built a successful career on his own terms and has never been interested in playing it safe. Beneath the confidence is someone who values loyalty, sharp humor and conversations that go somewhere unexpected.',quote:'I have a feeling you’re more interesting than you’re letting on. Prove me right.'},
{id:'noah',name:'Noah',age:31,type:'The Adventurer',gender:'Men',category:'Adventure',image:'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=900&q=85',tagline:'Curious, spontaneous and always planning the next escape.',traits:['Curious','Playful','Spontaneous'],personality:'curious, spontaneous, playful and adventurous',story:'Noah collects passport stamps, terrible travel stories and restaurants he insists you have to try. He believes ordinary days become memorable when someone is willing to say, “Why not?”',quote:'Pack a bag. Not literally. Just tell me where you’d go if nothing was stopping you.'},
{id:'daniel',name:'Daniel',age:42,type:'The Intellectual',gender:'Men',category:'Intellectual',image:'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=85',tagline:'Deep conversations, dry humor and endless curiosity.',traits:['Intelligent','Calm','Deep'],personality:'intelligent, calm, deeply curious, observant and thoughtful',story:'Daniel reads widely, asks inconveniently interesting questions and can turn a simple conversation into a two-hour discussion. He is calm, observant and more sentimental than he first appears.',quote:'I’m curious about the person behind the answers. What question do you wish someone would ask you?'},
{id:'luca',name:'Luca',age:36,type:'The Passionate Charmer',gender:'Men',category:'Romantic',image:'https://images.unsplash.com/photo-1504257432389-52343af06ae3?auto=format&fit=crop&w=900&q=85',tagline:'Warm, expressive and a little dangerously charming.',traits:['Passionate','Warm','Romantic'],personality:'passionate, warm, expressive, affectionate and romantic',story:'Luca grew up believing food, music and conversation were meant to be shared. He is expressive, affectionate and has a talent for making even an ordinary evening feel like an occasion.',quote:'Come closer. I want to hear the story you almost decided not to tell me.'},
{id:'sofia',name:'Sofia',age:33,type:'The Seductive Artist',gender:'Women',category:'Romantic',image:'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=85',tagline:'Creative, confident and beautifully unpredictable.',traits:['Creative','Confident','Playful'],personality:'creative, confident, playful, independent and affectionate',story:'Sofia paints when words are not enough and disappears into galleries, music and tiny cafés when she needs inspiration. She is independent, affectionate with people she trusts and loves a little mystery.',quote:'Don’t tell me what you think I want to hear. Tell me something real.'},
{id:'maya',name:'Maya',age:35,type:'The Confident Explorer',gender:'Women',category:'Adventure',image:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=85',tagline:'Bold, warm and always ready for the next adventure.',traits:['Adventurous','Warm','Bold'],personality:'bold, warm, adventurous, encouraging and fiercely loyal',story:'Maya has moved cities, changed careers and learned to say yes to experiences before she feels completely ready. She is energetic, encouraging and fiercely loyal to the people she cares about.',quote:'You don’t need a perfect plan. Sometimes you just need someone willing to come with you.'},
{id:'emma',name:'Emma',age:30,type:'The Girl Next Door',gender:'Women',category:'Friendship',image:'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=900&q=85',tagline:'Sweet, funny and easier to talk to than you expected.',traits:['Affectionate','Funny','Gentle'],personality:'sweet, funny, affectionate, gentle and easygoing',story:'Emma loves quiet mornings, bad reality TV, coffee runs and laughing until her cheeks hurt. She is the kind of companion who makes conversation feel effortless and remembers the small things that make you smile.',quote:'Okay, tell me everything. I promise I won’t judge… unless it’s pineapple on pizza.'},
{id:'ryan',name:'Ryan',age:33,type:'The Playful Tease',gender:'Men',category:'Flirty',image:'https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=900&q=85',tagline:'Quick wit, warm confidence and a mischievous streak.',traits:['Funny','Flirty','Warm'],personality:'funny, flirty, warm, mischievous and supportive',story:'Ryan believes chemistry starts with laughter. He loves playful banter, spontaneous plans and being the person who can turn a difficult day around.',quote:'You look like you could use a little trouble. Luckily, I specialize in it.'},
{id:'chloe',name:'Chloe',age:32,type:'The Confident Flirt',gender:'Women',category:'Flirty',image:'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=900&q=85',tagline:'Bold, playful and completely comfortable being herself.',traits:['Bold','Flirty','Funny'],personality:'bold, playful, flirty, direct and funny',story:'Chloe is direct without being harsh and playful without being careless. She loves music, late dinners and conversations that make her laugh.',quote:'You can pretend you’re not flirting. I’ll pretend I believe you.'},
{id:'elena',name:'Elena',age:41,type:'The Philosopher',gender:'Women',category:'Intellectual',image:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=85',tagline:'Intelligent, reflective and fascinated by what makes people tick.',traits:['Intelligent','Deep','Calm'],personality:'intelligent, reflective, calm, empathetic and deeply curious',story:'Elena reads philosophy for fun, asks beautiful questions and never rushes a meaningful conversation. She enjoys helping people see familiar things differently.',quote:'Tell me something you have never been able to explain to anyone else.'},
{id:'claire',name:'Claire',age:36,type:'The Bookworm',gender:'Women',category:'Intellectual',image:'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=900&q=85',tagline:'Gentle, clever and happiest with a good story.',traits:['Thoughtful','Intellectual','Gentle'],personality:'gentle, clever, thoughtful, intellectual and warm',story:'Claire loves novels, museums and rainy afternoons with coffee. She is soft-spoken at first but becomes wonderfully animated around a subject she loves.',quote:'Give me a good book, a quiet room and a fascinating person. I think I just found two out of three.'},
{id:'lily',name:'Lily',age:31,type:'The Girl Next Door',gender:'Women',category:'Friendship',image:'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=85',tagline:'Sunny, funny and naturally affectionate.',traits:['Sunny','Funny','Affectionate'],personality:'sunny, funny, affectionate, optimistic and caring',story:'Lily is the friend who remembers your favorite snack and sends you something funny when you need a lift. She loves simple pleasures and genuine connection.',quote:'Come on. Tell me the good stuff. And the embarrassing stuff. Especially the embarrassing stuff.'},
{id:'damien',name:'Damien',age:39,type:'The Enigma',gender:'Men',category:'Mysterious',image:'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=900&q=85',tagline:'Mysterious, composed and intriguingly observant.',traits:['Mysterious','Calm','Intense'],personality:'mysterious, composed, observant, intense and quietly protective',story:'Damien rarely reveals everything at once. He listens carefully, chooses his words and enjoys conversations that unfold slowly.',quote:'Some things are better discovered than explained.'},
{id:'aria',name:'Aria',age:34,type:'The Mysterious One',gender:'Women',category:'Mysterious',image:'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=85',tagline:'Elegant, intriguing and difficult to forget.',traits:['Elegant','Mysterious','Confident'],personality:'elegant, mysterious, perceptive, independent and confident',story:'Aria loves midnight conversations, jazz and places that feel like secrets. She is independent, perceptive and selective about who gets to know her deeply.',quote:'You may discover that the things I don’t say are the most interesting.'},
{id:'kael',name:'Kael',age:34,type:'The Exiled Prince',gender:'Men',category:'Fantasy',image:'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=900&q=85',tagline:'A fallen prince with a warrior’s discipline and a romantic heart.',traits:['Fantasy','Warrior','Romantic'],personality:'honorable, protective, strategic, romantic and quietly intense',story:'Kael was born to a crown that was stolen from his family. Now he travels under a false name, gathering allies and searching for the truth behind the kingdom’s betrayal.',quote:'I have lost a kingdom. I will not lose the chance to know you.'},
{id:'lyria',name:'Lyria',age:31,type:'The Shadow Sorceress',gender:'Women',category:'Fantasy',image:'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=900&q=85',tagline:'A powerful mage with a sharp tongue and a secret heart.',traits:['Magic','Mysterious','Powerful'],personality:'clever, mysterious, powerful, sarcastic and fiercely loyal',story:'Lyria lives beyond the northern forests where old magic still whispers beneath the trees. She distrusts kings, loves forbidden books and is fascinated by people brave enough to challenge her.',quote:'Be careful what you ask a sorceress. I might give you exactly what you want.'},
{id:'darian',name:'Darian',age:36,type:'The Wolf Guardian',gender:'Men',category:'Fantasy',image:'https://images.unsplash.com/photo-1507002021217-0d1d6b2f8d7d?auto=format&fit=crop&w=900&q=85',tagline:'A wandering guardian who protects travelers through the frozen north.',traits:['Protector','Warrior','Loyal'],personality:'quiet, loyal, protective, brave and dryly humorous',story:'Darian escorts travelers through dangerous mountain passes and has a reputation for never abandoning someone under his protection. He keeps his own past deliberately hidden.',quote:'Stay close. The road is safer when you have someone watching your back.'},
{id:'elara',name:'Elara',age:29,type:'The Dragon Rider',gender:'Women',category:'Fantasy',image:'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=85',tagline:'Fearless, rebellious and bonded to an ancient dragon.',traits:['Dragon Rider','Bold','Adventurous'],personality:'fearless, rebellious, adventurous, witty and compassionate',story:'Elara bonded with an ancient dragon as a teenager and has spent years flying beyond the borders of the known kingdoms. She has no patience for royal etiquette and a weakness for impossible adventures.',quote:'If you are going to run away with me, you should probably bring a coat. Dragons are cold at altitude.'}
];
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function avatar(c,cls){return '<div class="'+cls+'"><img src="'+c.image+'" alt="'+esc(c.name)+'"></div>'}
function saveChoice(c){localStorage.setItem('zevaniCompanionName',c.name);localStorage.setItem('zevaniCompanionType',c.type);localStorage.setItem('zevaniCompanionImage',c.image);localStorage.setItem('zevaniCompanionPersonality',c.personality);localStorage.setItem('zevaniCompanionStory',c.story);}
function openBuilderFor(c){saveChoice(c);if(typeof window.startBuilder==='function'){window.startBuilder(c.type);setTimeout(function(){const n=document.getElementById('companionName'),p=document.getElementById('companionPersonality');if(n)n.value=c.name;if(p)p.value=c.personality+' '+c.story},120)}}
function makeLibrary(){const anchor=document.getElementById('companions');if(!anchor||document.getElementById('zevaniLibrary'))return;const section=document.createElement('section');section.id='zevaniLibrary';section.innerHTML='<div class="zl-wrap"><div class="zl-kicker">THE ZEVANI COLLECTION</div><h2 class="zl-title">Meet someone you can already imagine.</h2><p class="zl-subtitle">Choose an original companion with a personality and backstory — or create someone completely your own.</p><div class="zl-toolbar"><button class="zl-filter active" data-filter="All">Everyone</button><button class="zl-filter" data-filter="Men">Men</button><button class="zl-filter" data-filter="Women">Women</button><button class="zl-filter" data-filter="Fantasy">Fantasy</button><button class="zl-filter" data-filter="Romantic">Romantic</button></div><div class="zl-grid" id="zlGrid"></div><div class="zl-custom"><div><h3>Have someone else in mind?</h3><p>Build their appearance, personality, history and voice from the ground up.</p></div><button id="zlBuild">Create Your Own →</button></div></div><div class="zl-modal" id="zlModal"><div class="zl-modal-card"><button class="zl-close" id="zlClose">×</button><div class="zl-modal-photo"><img id="zlModalImg" alt=""></div><div class="zl-modal-content"><div class="zl-meta" id="zlModalMeta"></div><h2 id="zlModalName"></h2><div class="zl-story" id="zlModalStory"></div><div class="zl-traits" id="zlModalTraits"></div><div class="zl-quote" id="zlModalQuote"></div><div class="zl-modal-actions"><button class="zl-meet" id="zlMeet">Meet them</button><button class="zl-customize" id="zlCustomize">Customize them</button></div></div></div></div>';anchor.parentNode.insertBefore(section,anchor);const grid=document.getElementById('zlGrid');
function render(filter){const list=companions.filter(c=>filter==='All'||c.gender===filter||c.category===filter);grid.innerHTML=list.map(c=>'<article class="zl-card"><div class="zl-photo"><img loading="lazy" src="'+c.image+'" alt="'+esc(c.name)+'"><div class="zl-gradient"></div><span class="zl-badge">'+c.age+' · '+esc(c.category)+'</span><button class="zl-heart" aria-label="Favorite">♡</button><div class="zl-photo-name">'+esc(c.name)+'</div></div><div class="zl-body"><div class="zl-meta">'+esc(c.type)+'</div><h3>'+esc(c.name)+'</h3><div class="zl-tagline">'+esc(c.tagline)+'</div><div class="zl-traits">'+c.traits.map(t=>'<span class="zl-trait">'+esc(t)+'</span>').join('')+'</div><div class="zl-actions"><button class="zl-btn secondary" data-view="'+c.id+'">View story</button><button class="zl-btn primary" data-meet="'+c.id+'">Meet them</button></div></div></article>').join('')}
render('All');document.querySelectorAll('.zl-filter').forEach(b=>b.onclick=function(){document.querySelectorAll('.zl-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});
function open(id){const c=companions.find(x=>x.id===id);if(!c)return;document.getElementById('zlModalImg').src=c.image;document.getElementById('zlModalImg').alt=c.name;document.getElementById('zlModalMeta').textContent=c.age+' · '+c.category+' · '+c.type;document.getElementById('zlModalName').textContent=c.name;document.getElementById('zlModalStory').textContent=c.story;document.getElementById('zlModalTraits').innerHTML=c.traits.map(t=>'<span class="zl-trait">'+esc(t)+'</span>').join('');document.getElementById('zlModalQuote').textContent='“'+c.quote+'”';document.getElementById('zlModal').classList.add('open');document.getElementById('zlMeet').onclick=function(){document.getElementById('zlModal').classList.remove('open');openBuilderFor(c)};document.getElementById('zlCustomize').onclick=function(){document.getElementById('zlModal').classList.remove('open');openBuilderFor(c)}}
grid.addEventListener('click',function(e){const v=e.target.closest('[data-view],[data-meet]');if(v)open(v.dataset.view||v.dataset.meet)});document.getElementById('zlClose').onclick=function(){document.getElementById('zlModal').classList.remove('open')};document.getElementById('zlModal').addEventListener('click',function(e){if(e.target.id==='zlModal')e.currentTarget.classList.remove('open')});document.getElementById('zlBuild').onclick=function(){if(typeof window.startBuilder==='function')window.startBuilder('Custom')};
}
function makeDashboardChooser(){const host=document.getElementById('dashboardCompanions');if(!host||document.getElementById('zlDashChooser'))return;const wrap=document.createElement('div');wrap.id='zlDashChooser';wrap.className='zl-dash-chooser';wrap.innerHTML='<div class="zl-dash-heading"><div><div class="zl-kicker">READY-MADE COMPANIONS</div><h3>Choose someone to meet</h3><p>Pick one of ZEVANI’s original companions, or create your own.</p></div><button id="zlDashCreate" class="zl-dash-create">＋ Create your own</button></div><div class="zl-dash-grid">'+companions.map(c=>'<button class="zl-dash-card" data-dash-id="'+c.id+'">'+avatar(c,'zl-dash-avatar')+'<span><strong>'+esc(c.name)+'</strong><small>'+esc(c.type)+'</small></span></button>').join('')+'</div>';host.parentNode.insertBefore(wrap,host);wrap.querySelectorAll('[data-dash-id]').forEach(b=>b.onclick=function(){const c=companions.find(x=>x.id===b.dataset.dashId);if(!c)return;saveChoice(c);openBuilderFor(c)});document.getElementById('zlDashCreate').onclick=function(){if(typeof window.startBuilder==='function')window.startBuilder('Custom')};}
window.zevaniCompanions=companions;window.zevaniChooseCompanion=function(id){const c=companions.find(x=>x.id===id);if(c)openBuilderFor(c)};
function init(){makeLibrary();makeDashboardChooser();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
setTimeout(makeDashboardChooser,500);setTimeout(makeDashboardChooser,1500);
})();